# service-config 服务端配置

#配置eureka 的注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

    # EurekaClient每隔多久从EurekaServer拉取一次服务列表，默认30秒，这里修改为2秒钟从注册中心拉取一次
    registry-fetch-interval-seconds: 2
  #租约期限以及续约期限的配置
  instance:
    prefer-ip-address: true

    #租约到期，服务失效时间，默认值90秒，服务超过90秒没有发生心跳，EurekaServer会将服务从列表移除
    #这里修改为6秒
    lease-expiration-duration-in-seconds: 6
    #租约续约间隔时间，默认30秒，这里修改为3秒钟
    lease-renewal-interval-in-seconds: 3

#这里是Ribbon缓存实例列表的刷新间隔，默认30秒钟，这里修改为每秒钟刷新一次实例信息
ribbon:
  ServerListRefreshInterval: 1000

#服务端口
server:
  port: 8769

spring:
  application:
    name: service-config #服务名称

  profiles:
    active: native #设置为本地启动的方式，而不是通过git
  cloud:
    config:
      server:
        native:
          #搜索位置(可用的通配符有3个，分别是: {application} 映射客户端spring.application.name, {profile} 映射客户端spring.profiles.active[多个以逗号分隔], {label}这是服务器端功能，标记了一组“版本化”的配置文件。 )
          search-locations: classpath:/{profile}